### ISSUE TITLE
IZUSVR does not have access to profile BPX.JOBNAME

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-test#104]
The latest successful build issues this error message
```
Check IZUSVR/IZUADMIN has at least READ access to BPX.JOBNAME
Warning: User IZUSVR does not have access to profile BPX.JOBNAME
You will not be able to set job names using the _BPX_JOBNAME environment variable
```
The test does not fail.  However, this error means that the jobnames for the spawned STC tasks will be wrong, so some of the `zowe-verify.sh` checks fail, rendering them invalid.

**Comment by John-A-Davies** [comment]
This is the first item in the `Prerequisites` section of the User Guide, so we should check this in `zowe-check-prereqs.sh`.

**Comment by jackjia-ibm** [comment]
This should have been resolved.
