### ISSUE TITLE
Startup of ZOWESVR did not stop previous ZOWESVR first

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-test#112]
The Jenkins script issued
```
S ZWESIS01
[install-zowe.sh] start Zowe ...
S ZOWESVR,SRVRPATH='/S0W1/tmp/usr/lpp/zowe',JOBNAME=ZOWE1SV
```
but the prior uninstall step used the old STC names, so the jobs were not stopped.
```
[uninstall-zowe.sh] stopping ZWESIS01 ...
P ZWESIS01
[uninstall-zowe.sh] stopping Zowe ...
C ZOWESVR
S0W1      2019253  03:43:28.32  STC05644   IEE341I ZOWESVR           NOT ACTIVE
ISF754I Command 'SET CONSOLE MYCONS' generated from associated variable ISFCONS.
C ZOWESV1
S0W1      2019253  03:43:29.73  STC05643   IEE341I ZOWESV1           NOT ACTIVE
```

**Comment by John-A-Davies** [comment]
The basic fix for this is to set
```
DEFAULT_CI_ZOWE_JOB_NAME=ZOWE1SV
```
in `uninstall-zowe.sh`, but this does not fix the case where more than one job of that name is running.

**Comment by John-A-Davies** [comment]
Stopping *all* Zowe processes during uninstall would be an enhancement.

In future, we will test multiple instances; ZOWE1SV, ZOWE2SV etc, so we need to be sure to stop only the right jobs.

**Comment by jackjia-ibm** [comment]
This should be fixed with the `KNOWN_ZOWE_JOB_NAMES` variable is introduced to the uninstall-zowe.sh script.
