### ISSUE TITLE
Create ZWE* user IDs on Marist for the build pipeline

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-test#145]
Zowe is moving away from the IZUUSR and IZUADMIN user IDs towards dedicated ones.  These will need to be created on marist in advanced the pipeline changes

ZWEADMIN     * group for Zowe administrators
ZWESVUSR     * userid for Zowe started task
ZWESIUSR        * userid for xmem started task

The user ID  ZOWEAD3 that runs the pipeline install will need to be part of the ZWEADMIN user group as the install script performs chgroup commands.  

More details are in the file https://github.com/zowe/zowe-install-packaging/blob/staging/files/jcl/ZWESECUR.jcl

**Comment by jackjia-ibm** [comment]
@Joe-Winchester @stevenhorsman `ZWEADMIN` group and `ZWESVUSR` `ZWESIUSR` users are created. I did a quick check on RACF definition looks ok to me. Please see if they works well.

**Comment by jackjia-ibm** [comment]
I believe this has been resolved. Please re-open otherwise.
