### ISSUE TITLE
Pipeline needs ZWEADMIN group

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-test#152]
The ZWESECUR job tries to run ALTGROUP 

```
14:22:06 [wrap_call] tsocmd ALTGROUP ZWEADMIN OMVS(AUTOGID) DATA('ZOWE ADMINISTRATORS') >>>
14:22:06 ICH20016I NOT AUTHORIZED TO SPECIFY THE DATA OR NODATA KEYWORDS.
14:22:06 IRR52127I Field level access checking failed for segment OMVS. 
14:22:06 ICH20021I PROFILE UNCHANGED. NOT AUTHORIZED TO ALTER SEGMENT FOR GROUP ZWEADMIN
```
but the install user ZOWEAD3 does not have authorisation to do that, so we suppress all user- and group-oriented commands.  

Therefore we need to have those groups set up in the way that ZWESECUR requires.

**Comment by jackjia-ibm** [comment]
This should be done. Please verify.

**Comment by jackjia-ibm** [comment]
I believe this has been resolved. Please re-open otherwise.
