### ISSUE TITLE
Zowe-install-test is using the incorrect version of ZWESECUR

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-test#154]
- [ ] create-security-defn.sh:127-154 is running the ZWESECUR from uss, not the PDS member created - this is why SMPE doesn’t work and means that the convenience build is not checking the install process.

- [ ] It is also still incorrectly calling the old install-xmem code in the install directory(this code is removed in https://github.com/zowe/zowe-install-packaging/pull/1021) as references by Jack in slack
> https://github.com/zowe/zowe-install-test/blob/staging/scripts/install-zowe.sh#L510. the install-xmem-server.sh is calling zowe-xmem-apf.sh as shown in https://github.com/zowe/zowe-install-test/blob/staging/scripts/install-xmem-server.sh#L154

**Comment by John-A-Davies** [comment]
Working on that now.
