### ISSUE TITLE
Create performance test cases and track result

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-test#93]
Load test tool could be wrk/ab/time etc.

https://wiki.jenkins.io/display/JENKINS/Performance+Plugin could be useful to display result.

**Comment by NakulManchanda** [comment]
All performance related discussion is here.
It contains test cases etc
https://ibm.ent.box.com/folder/82548817932

**Comment by NakulManchanda** [comment]
Created this new utility, to process results from divideRMF
https://github.ibm.com/Nakul-Manchanda/DivideRMFProcessing

**Comment by jackjia-ibm** [comment]
This work had been consolidated into Epic https://github.com/zowe/zowe-install-packaging/issues/617
